development:
  adapter: postgresql
  database: masconaso_dev
  host: localhost
  username: postgres
  password: jhlive
test:
  adapter: postgresql
  database: masconaso_test
  host: localhost
  username: postgres
  password: jhlive

production:
  adapter: postgresql
  database: masconaso_prod
  host: localhost
  username: postgres
  password: jhlive
